---
version: 2
multicolumn: true
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Discriminator High Level/Architecture.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/246441/articles/327603/master/folder/figures/Discriminator
      High Level"
    url: "/users/246441/articles/327603/master/file/figures/Discriminator%20High%20Level/Architecture.png"
