---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Discriminator High Level/Discriminator High Level.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/246441/articles/327603/master/file/figures/Discriminator%20High%20Level/Discriminator%20High%20Level.png"
    folder_url: "/users/246441/articles/327603/master/folder/figures/Discriminator
      High Level"
