---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/conditioning_evaluation_results/conditioning_evaluation_results.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/246441/articles/327603/master/file/figures/conditioning_evaluation_results/conditioning_evaluation_results.png"
